# Parameteres for elastic  net model
elastic_net:
  alpha: 0.1
  l1_ratio: 0.5
  max_iter: 1000

# Parameteres for  lasso model
lasso:
  alpha: 0.1
  max_iter: 1000

# Parameteres for  random forest model
random_forest:
  max_depth: 10
  min_samples_leaf: 2
  min_samples_split: 5
  n_estimators: 100
  random_state: 42

# Parameteres for  ridge model
ridge:
  alpha: 1.0
  solver: auto

# Parameters for xgboost model
xgboost:
  learning_rate: 0.1
  max_depth: 5
  n_estimators: 100
  random_state: 42
